# Generated by Django 6.0.6 on 2026-07-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=100)),
                ('parked_hours', models.IntegerField()),
                ('paid_amount', models.FloatField()),
                ('status', models.CharField(choices=[('Parked', 'Parked'), ('Free', 'Free')], max_length=10)),
            ],
        ),
    ]
